### ISSUE TITLE
Initial job has not accepted any resources...

### ISSUE THREAD

**Issue by Tellz777** [oap-project/raydp#299] opened 2023-01-24 22:23 UTC
Hi, guys. 

I have Ray-cluster installed in Kubernetes:

```
1 master (2 CPU/10GB memory)
4 workers (2 CPU/10GB memory each)
```
It uses a custom image of Ray I've builded. 

Dockerfile:

```
FROM rayproject/ray:2.2.0
USER root
RUN apt-get update && apt-get install -y openjdk-11-jdk \
    && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
RUN pip install raydp==1.5.0
```
Im trying to run your example of spark job on my remote Ray cluster (locally it works perfect).

```
import ray
import raydp

ray.init(address='ray://<my-remote-kuberay-head-svc>:10001')

spark = raydp.init_spark(app_name='RayDP Example', num_executors=1, executor_cores=1, executor_memory='1GB')
spark.sparkContext.setLogLevel("INFO")
df = spark.createDataFrame([('look',), ('spark',), ('tutorial',), ('spark',), ('look', ), ('python', )], ['word'])
df.show()
word_count = df.groupBy('word').count()
word_count.show()

raydp.stop_spark()
```

And starting to receive this WARN message repeatedly:  "Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources"

As I see from the logs it starts Spark UI locally on my laptop here: http://127.0.0.1:4040/

Spark master logs:
```
:actor_name:RayDPSparkMaster
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/jars/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ray/anaconda3/lib/python3.7/site-packages/ray/jars/ray_dist.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
```
Ray app master logs:
```
2023-01-24 13:50:09,765 WARN NativeCodeLoader [main]: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2023-01-24 13:50:09,863 INFO SecurityManager [main]: Changing view acls to: root
2023-01-24 13:50:09,864 INFO SecurityManager [main]: Changing modify acls to: root
2023-01-24 13:50:09,864 INFO SecurityManager [main]: Changing view acls groups to: 
2023-01-24 13:50:09,865 INFO SecurityManager [main]: Changing modify acls groups to: 
2023-01-24 13:50:09,865 INFO SecurityManager [main]: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
2023-01-24 13:50:10,247 INFO Utils [main]: Successfully started service 'RAY_RPC_ENV' on port 44937.
2023-01-24 13:50:16,055 INFO RayAppMaster$RayAppMasterEndpoint [dispatcher-event-loop-1]: Registering app RayDP Example
2023-01-24 13:50:16,059 INFO RayAppMaster$RayAppMasterEndpoint [dispatcher-event-loop-1]: Registered app RayDP Example with ID app-20230124135016057
2023-01-24 13:50:16,065 INFO RayAppMaster$RayAppMasterEndpoint [dispatcher-event-loop-1]: Requesting Spark executor with Ray logical resource { CPU: 1.0 }..
```
RayDP executor logs:
```
2023-01-24 13:50:19,126 WARN NativeCodeLoader [main]: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2023-01-24 13:50:19,206 INFO SecurityManager [main]: Changing view acls to: root
2023-01-24 13:50:19,206 INFO SecurityManager [main]: Changing modify acls to: root
2023-01-24 13:50:19,207 INFO SecurityManager [main]: Changing view acls groups to: 
2023-01-24 13:50:19,207 INFO SecurityManager [main]: Changing modify acls groups to: 
2023-01-24 13:50:19,208 INFO SecurityManager [main]: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
2023-01-24 13:50:19,609 INFO TransportClientFactory [netty-rpc-connection-0]: Successfully created connection to /10.108.183.48:44937 after 99 ms (0 ms spent in bootstraps)
2023-01-24 13:50:19,780 INFO RayDPExecutor [main]: Executor: 0 register to app master success
2023-01-24 13:50:19,801 ERROR RayDPExecutor [Thread-2]: Create application dir: /tmp/ray/session_2023-01-24_13-45-40_775733_8/app-20230124135016057 failed, remaining times: 2
2023-01-24 13:50:19,802 INFO RayDPExecutor [Thread-2]: Set user.dir to /tmp/ray/session_2023-01-24_13-45-40_775733_8/app-20230124135016057/0
2023-01-24 13:50:19,810 INFO RayDPExecutor [Thread-3]: Started daemon with process name: 1279@kuberay-worker-workergroup-rc52g
2023-01-24 13:50:19,815 INFO SignalUtils [Thread-3]: Registering signal handler for TERM
2023-01-24 13:50:19,817 INFO SignalUtils [Thread-3]: Registering signal handler for HUP
2023-01-24 13:50:19,817 INFO SignalUtils [Thread-3]: Registering signal handler for INT
2023-01-24 13:50:19,864 WARN RayDPExecutor [Thread-3]: null
2023-01-24 13:50:19,864 ERROR DefaultRayRuntimeFactory [Thread-3]: Uncaught worker exception in thread Thread[Thread-3,5,main]
java.lang.reflect.UndeclaredThrowableException: null
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1894) ~[hadoop-client-api-3.3.2.jar:?]
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.executor.RayDPExecutor.org$apache$spark$executor$RayDPExecutor$$serveAsExecutor(RayDPExecutor.scala:203) ~[raydp-1.5.0.jar:?]
	at org.apache.spark.executor.RayDPExecutor$$anon$1.run(RayDPExecutor.scala:130) ~[raydp-1.5.0.jar:?]
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.executor.RayDPExecutor.$anonfun$serveAsExecutor$3(RayDPExecutor.scala:208) ~[raydp-1.5.0.jar:?]
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23) ~[scala-library-2.12.15.jar:?]
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985) ~[scala-library-2.12.15.jar:?]
	at scala.collection.immutable.Range.foreach(Range.scala:158) ~[scala-library-2.12.15.jar:?]
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984) ~[scala-library-2.12.15.jar:?]
	at org.apache.spark.executor.RayDPExecutor.$anonfun$serveAsExecutor$1(RayDPExecutor.scala:206) ~[raydp-1.5.0.jar:?]
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at javax.security.auth.Subject.doAs(Subject.java:423) ~[?:?]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878) ~[hadoop-client-api-3.3.2.jar:?]
	... 3 more
Caused by: java.io.IOException: Failed to connect to /127.0.0.1:60127
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288) ~[spark-network-common_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218) ~[spark-network-common_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230) ~[spark-network-common_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198) ~[spark-core_2.12-3.3.1.jar:3.3.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:60127
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.74.Final.jar:4.1.74.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```
PyCharm output:
```
/opt/miniconda3/envs/conda3-7/bin/python /Users/ilyaz/Desktop/kuberay/helm-chart/actor.py 
(RayDPSparkMaster pid=1051, ip=10.108.183.48) Setting default log level to "WARN".
(RayDPSparkMaster pid=1051, ip=10.108.183.48) To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
(RayDPSparkMaster pid=1051, ip=10.108.183.48) SLF4J: Class path contains multiple SLF4J bindings.
(RayDPSparkMaster pid=1051, ip=10.108.183.48) SLF4J: Found binding in [jar:file:/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/jars/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
(RayDPSparkMaster pid=1051, ip=10.108.183.48) SLF4J: Found binding in [jar:file:/home/ray/anaconda3/lib/python3.7/site-packages/ray/jars/ray_dist.jar!/org/slf4j/impl/StaticLoggerBinder.class]
(RayDPSparkMaster pid=1051, ip=10.108.183.48) SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
(RayDPSparkMaster pid=1051, ip=10.108.183.48) SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
(RayDPSparkMaster pid=1051, ip=10.108.183.48) kuberay-head-svc:6379
(raylet, ip=10.108.183.48) SLF4J: Class path contains multiple SLF4J bindings.
(raylet, ip=10.108.183.48) SLF4J: Found binding in [jar:file:/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/jars/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
(raylet, ip=10.108.183.48) SLF4J: Found binding in [jar:file:/home/ray/anaconda3/lib/python3.7/site-packages/ray/jars/ray_dist.jar!/org/slf4j/impl/StaticLoggerBinder.class]
(raylet, ip=10.108.183.48) SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
(raylet, ip=10.108.183.48) SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/miniconda3/envs/conda3-7/lib/python3.7/site-packages/ray/jars/ray_dist.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/miniconda3/envs/conda3-7/lib/python3.7/site-packages/pyspark/jars/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-01-25 00:50:13,665 WARN NativeCodeLoader [main]: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2023-01-25 00:50:16,465 INFO SharedState [Thread-4]: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
2023-01-25 00:50:16,468 INFO SharedState [Thread-4]: Warehouse path is 'file:/Users/ilyaz/Desktop/kuberay/helm-chart/spark-warehouse'.
2023-01-25 00:50:16,488 INFO ContextHandler [Thread-4]: Started o.s.j.s.ServletContextHandler@5b4890f4{/SQL,null,AVAILABLE,@Spark}
2023-01-25 00:50:16,488 INFO ContextHandler [Thread-4]: Started o.s.j.s.ServletContextHandler@12a5a7d9{/SQL/json,null,AVAILABLE,@Spark}
2023-01-25 00:50:16,489 INFO ContextHandler [Thread-4]: Started o.s.j.s.ServletContextHandler@5fc4b28a{/SQL/execution,null,AVAILABLE,@Spark}
2023-01-25 00:50:16,490 INFO ContextHandler [Thread-4]: Started o.s.j.s.ServletContextHandler@7ae2ab85{/SQL/execution/json,null,AVAILABLE,@Spark}
2023-01-25 00:50:16,491 INFO ContextHandler [Thread-4]: Started o.s.j.s.ServletContextHandler@62005b81{/static/sql,null,AVAILABLE,@Spark}
(raylet, ip=10.108.183.48) SLF4J: Class path contains multiple SLF4J bindings.
(raylet, ip=10.108.183.48) SLF4J: Found binding in [jar:file:/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/jars/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
(raylet, ip=10.108.183.48) SLF4J: Found binding in [jar:file:/home/ray/anaconda3/lib/python3.7/site-packages/ray/jars/ray_dist.jar!/org/slf4j/impl/StaticLoggerBinder.class]
(raylet, ip=10.108.183.48) SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
(raylet, ip=10.108.183.48) SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-01-25 00:50:20,951 INFO CodeGenerator [Thread-4]: Code generated in 246.614654 ms
2023-01-25 00:50:20,977 INFO SparkContext [Thread-4]: Starting job: showString at NativeMethodAccessorImpl.java:0
2023-01-25 00:50:20,992 INFO DAGScheduler [dag-scheduler-event-loop]: Got job 0 (showString at NativeMethodAccessorImpl.java:0) with 1 output partitions
2023-01-25 00:50:20,992 INFO DAGScheduler [dag-scheduler-event-loop]: Final stage: ResultStage 0 (showString at NativeMethodAccessorImpl.java:0)
2023-01-25 00:50:20,992 INFO DAGScheduler [dag-scheduler-event-loop]: Parents of final stage: List()
2023-01-25 00:50:20,993 INFO DAGScheduler [dag-scheduler-event-loop]: Missing parents: List()
2023-01-25 00:50:20,997 INFO DAGScheduler [dag-scheduler-event-loop]: Submitting ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0), which has no missing parents
2023-01-25 00:50:21,115 INFO MemoryStore [dag-scheduler-event-loop]: Block broadcast_0 stored as values in memory (estimated size 11.7 KiB, free 366.3 MiB)
2023-01-25 00:50:21,595 INFO MemoryStore [dag-scheduler-event-loop]: Block broadcast_0_piece0 stored as bytes in memory (estimated size 6.3 KiB, free 366.3 MiB)
2023-01-25 00:50:21,599 INFO BlockManagerInfo [dispatcher-BlockManagerMaster]: Added broadcast_0_piece0 in memory on 127.0.0.1:60131 (size: 6.3 KiB, free: 366.3 MiB)
2023-01-25 00:50:21,603 INFO SparkContext [dag-scheduler-event-loop]: Created broadcast 0 from broadcast at DAGScheduler.scala:1513
2023-01-25 00:50:21,619 INFO DAGScheduler [dag-scheduler-event-loop]: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
2023-01-25 00:50:21,620 INFO TaskSchedulerImpl [dag-scheduler-event-loop]: Adding task set 0.0 with 1 tasks resource profile 0
2023-01-25 00:50:36,649 WARN TaskSchedulerImpl [task-starvation-timer]: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
2023-01-25 00:50:51,647 WARN TaskSchedulerImpl [task-starvation-timer]: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources.
...
```
Thanks for any help!

**Comment by vladosby** [comment] 2023-01-25 00:09
I also faced with this issue. It looks like by some reason ray think that spark driver works on the local machine. If you will get spark config like this `spark.sparkContext.getConf().getAll()`, you will see that you have parameter `spark.driver.host` that points to localhost(127.0.0.1).  

If somebody knows is it valid behaviour or not please comment.

As work around for now, I can suggest to create Ray Actor that will create spark session on cluster.
Please see example:
```
ray.init(address="ray_cluster", runtime_env={"working_dir": "any jars that can be needed for app"})


@ray.remote
class PySparkApp:
    spark = None

    def __init__(self):
        self.spark = raydp.init_spark(
            app_name='My spark app',
            num_executors=2,
            executor_cores=2,
            executor_memory='4GB')

    def read_csv(self, path: str):
        # collect here just for debug purpose, so be careful when you have big dataset  
        return self.spark.read.csv(path).collect()


spark_app = PySparkApp.remote()

df = ray.get(
    spark_app.read_csv.remote("some_path"))
print(df)
```

**Comment by kira-lin** [comment] 2023-01-30 06:27
> If somebody knows is it valid behaviour or not please comment.

Yes, spark driver is expected to be local. Is this a problem? If you want spark driver to be in the remote cluster, you should wrap it in an actor just like you do.

**Comment by vladosby** [comment] 2023-01-30 10:04
> Yes, spark driver is expected to be local. Is this a problem? If you want spark driver to be in the remote cluster, you should wrap it in an actor just like you do.

Probably I miss something or it is a bug, but if you look at the first comment, you will see that executors trying to connect to the driver from the remote executors:
`Caused by: java.io.IOException: Failed to connect to /127.0.0.1:60127`

So, all examples from documentation do not work when ray init use remote cluster:
`ray.init(address='ray://<my-remote-kuberay-head-svc>:10001')`

**Comment by kira-lin** [comment] 2023-01-31 05:46
I see. I think this is a bug, I'll look into it, thanks!

**Comment by kira-lin** [comment] 2023-02-07 01:45
hi @vladosby @Tellz777 ,
I have submitted a PR #301 to solve this issue. However, we have a problem on mac. Ray on Mac implement `ray.util.get_node_ip_address` to avoid secutiry popup. But we use this function to provide the local machine address as `spark.driver.host` to the spark cluster. Is this a problem for you? Are you using mac?

**Comment by vladosby** [comment] 2023-02-07 08:37
Hi @kira-lin,
Yes, We both use mac's.

**Comment by kira-lin** [comment] 2023-02-08 02:18
>  It looks like it sync environment only on driver node, but not on the workers

Can you elaborate more on this?

**Comment by kira-lin** [comment] 2023-02-13 08:30
We have merged the PR, can you try our nightly release(pip install --pre -U raydp) and see if you can connect? You can set the config `spark.driver.host` if the default value does not work.

**Comment by vladosby** [comment] 2023-02-13 09:00
> > It looks like it sync environment only on driver node, but not on the workers
> 
> Can you elaborate more on this?

For instance, I have code like this:
```
ray.init(address="ray://ray.ml-stage.dub:10001", runtime_env={"working_dir": "./model/output", "conda": "./environment.yaml"})

@ray.remote
class PySparkDriver:
    _model = None

    broadcasted_model = None
    predict_udf = None
    spark = None

    def __init__(self, model_path: str):
        from joblib import load

        self._model = load(model_path)

        self.spark = raydp.init_spark(
            app_name='Inference',
            num_executors=2,
            executor_cores=2,
            executor_memory='4GB',
            configs=None)

        self.predict_udf = F.udf(PySparkDriver.predict_data, IntegerType())
        PySparkDriver.broadcasted_model = self.spark.sparkContext.broadcast(self._model)
        
    @staticmethod
    def predict_data(*cols):
        return int(PySparkDriver.broadcasted_model.value.predict((cols,)))

    def predict_csv(self, path: str):
        df = self.spark.read.options(header="True").csv(path)
        processed_df = self.preprocess_single_row_data(df)
        return processed_df.withColumn("Prediction", self.predict_udf(*processed_df.columns)).collect()

    def preprocess_single_row_data(self, df):
        new_df = df.withColumn("Family", F.col('Parch') + F.col('SibSp')) \
            .withColumn("PassengerId", F.col("PassengerId").cast(IntegerType())) \
            .withColumn("Is_Alone", (F.col('Parch') + F.col('SibSp')) == 0) \
            .withColumn("Sex", F.when(F.col("Sex") == "male", 0).otherwise(1)) \
            .drop("Pclass", "Fare", "Cabin", "Fare_Category", "Name", "Salutation", "Ticket", "Embarked",
                  "SibSp", "Parch", "Age")
        return new_df       
        
driver = PySparkDriver.remote("gaussian_nb_model.pickle")

ds = ray.get(
    driver.predict_csv.remote("hdfs://user/vladislavki/test.csv"))         
```

environment.yaml like this:
```
name: ray-poc
channels:
  - defaults
dependencies:
  - python==3.7.13
  - pip
  - pyarrow>=6.0.1
  - pandas
  - pip:
    - scikit-learn==1.0.2
    - raydp

```
When you run this code, you will get error on worker/executor like this:
```
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/vladislavki/Documents/projects/others/ray-poc/src/pipeline_ray_and_pyspark.py", line 68, in predict_data
  File "/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/broadcast.py", line 186, in value
    self._value = self.load_from_path(self._path)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/broadcast.py", line 164, in load_from_path
    return self.load(f)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/broadcast.py", line 172, in load
    gc.enable()145ModuleNotFoundError: No module named 'sklearn'
```

**Comment by vladosby** [comment] 2023-02-13 09:33
> spark.driver.host

I installed new ray only locally and have the same error without adding any config and with specifying my ip in config like this:
```
spark_conf = {
"spark.driver.host": "my-ip"
}

spark = raydp.init_spark(
    app_name='`Remote model batch prediction`',
    num_executors=2,
    executor_cores=2,
    executor_memory='2GB',
    placement_group_strategy="SPREAD",
    configs=spark_conf)
```

But in both cases I have the same error:
`Connection refused: /127.0.0.1:51797`
By some reason it is trying to connect to localhost

**Comment by kira-lin** [comment] 2023-02-15 06:10
I see, you are using ray runtime environment. Are you installing ray like `pip install ray[default]`? If not, you can try this. If it's still  not working, you can ask ray community. 

> I installed new ray only locally and have the same error without adding any config and with specifying my ip in config like this

You can try our nightly release: `pip install --pre -U raydp`.  Please do this both locally and in the cluster.   There is no need to update ray, and ray version should be the same between local machine and the cluster.

**Comment by kira-lin** [comment] 2023-04-17 02:01
Have you solved the issue?

**Comment by vladosby** [comment] 2023-04-17 11:26
Hi, 
No, We cannot run it and decided move without ray.

**Comment by kira-lin** [comment] 2023-04-18 01:08
Alright, sorry we couldn't help

**Closed by kira-lin** 2023-04-18 01:08 UTC
